package com.fortyonestudio.realmexample;

import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;

/**
 * Created by Riris.
 */
public class User extends RealmObject {

    @PrimaryKey
    private int user_id;

    private String first_name;

    private String last_name;

    private String country;

    public User() {
    }

    public User(int user_id, String first_name, String last_name, String country) {
        this.country = country;
        this.first_name = first_name;
        this.last_name = last_name;
        this.user_id = user_id;
    }

    public User(String first_name, String last_name, String country ) {
        this.country = country;
        this.last_name = last_name;
        this.first_name = first_name;
    }

    // Standard getters & setters generated by your IDE…

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getFirst_name() {
        return first_name;
    }

    public void setFirst_name(String first_name) {
        this.first_name = first_name;
    }

    public String getLast_name() {
        return last_name;
    }

    public void setLast_name(String last_name) {
        this.last_name = last_name;
    }

    public int getUser_id() {
        return user_id;
    }

    public void setUser_id(int user_id) {
        this.user_id = user_id;
    }


}
